# Generated by Django 4.0.3 on 2022-06-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyyear', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('study_discription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expreance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workyear', models.CharField(max_length=100)),
                ('workas', models.CharField(max_length=100)),
                ('work_discription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funfact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameone_title', models.CharField(max_length=20)),
                ('nameone', models.IntegerField()),
                ('nametwo_title', models.CharField(max_length=20)),
                ('nametwo', models.IntegerField()),
                ('namethree_title', models.CharField(max_length=20)),
                ('namethree', models.IntegerField()),
                ('namefour_title', models.CharField(max_length=20)),
                ('namefour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Myskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_service_title', models.CharField(max_length=25)),
                ('first_service_Discription', models.TextField()),
                ('second_service_title', models.CharField(max_length=25)),
                ('second_service_Discription', models.TextField()),
                ('third_service_title', models.CharField(max_length=25)),
                ('third_service_Discription', models.TextField()),
                ('fourth_service_title', models.CharField(max_length=25)),
                ('fourth_service_Discription', models.TextField()),
                ('fifth_service_title', models.CharField(max_length=25)),
                ('ffith_service_Discription', models.TextField()),
                ('sixth_service_title', models.CharField(max_length=25)),
                ('sixth_service_Discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('first_auto', models.CharField(max_length=50)),
                ('second_auto', models.CharField(max_length=50)),
                ('my_short_discription', models.TextField(max_length=500)),
                ('my_cv', models.FileField(upload_to='mycv')),
                ('profilepic', models.ImageField(upload_to='profilepic')),
                ('About_me_description', models.TextField(max_length=1000)),
                ('DOB', models.DateField()),
                ('freelancer', models.CharField(max_length=10)),
                ('adderss', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
