# Generated by Django 4.0.3 on 2022-06-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(default='sulav pariyar portfolio', max_length=25),
        ),
    ]
